name: Build

on: [workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      # - name: Build
      #   uses: qcastel/github-actions-maven/actions/maven@master
      #   with:
      #     maven-args: "clean package"
      - name: Create JAR
        run: mvn package
